[package]
name = "blitz"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Kelley <jkelleyrtp@gmail.com>"]
description = "Native iced-wgpu based renderer for Dioxus"
license = "MIT/Apache-2.0"
repository = "https://github.com/DioxusLabs/blitz"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev = "020c4bf0f8f811178d7ef52637db7aa9071fa759" }
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", rev = "020c4bf0f8f811178d7ef52637db7aa9071fa759" }
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev = "020c4bf0f8f811178d7ef52637db7aa9071fa759" }
taffy = "0.1"
tokio = { version = "1.17.0", features = ["full"] }
parcel_css = "1.0.0-alpha.32"
cssparser = "0.29.2"
piet-wgpu = { git = "https://github.com/StarStarJ/piet-wgpu" }
tao = { version = "0.12.1", features = ["serde"] }
raw-window-handle = "0.4.2"
anymap = "0.12.1"
futures-util = "0.3.21"
fxhash = "0.2"
serde_json = "1.0.82"
serde = { version = "1.0.138", features = ["derive"] }
keyboard-types = "0.6.2"
